version: "3"
services:
   web:
      container_name: dnhn-web
      image: dotnethacknight
      ports:
         - "5000:80"
      depends_on:
         - db
   db:
      container_name: dnhn-db
      image: mcr.microsoft.com/mssql/server
      ports:
         - "1433:1433"
      volumes:
         - dnhn-sql-volume:/var/opt/mssql
      environment:
         ACCEPT_EULA: "Y"
         SA_PASSWORD: "!!DOTnetHACKnight!!"
volumes:
   dnhn-sql-volume:
